### PR TITLE
Implement full set of arithmetic operations

### PR DESCRIPTION
**Pull request by ObjectBoxPC**
Implement arithmetic operations including addition, subtraction, multiplication, and division.

See previous discussion at #1

### CODE REVIEW

**Comment by ObjectBoxPC** [comment]
In the previous discussion, I mentioned the `magnitude` crate as another crate that serves much of the same purpose as this one. In my current implementation, there are some design differences in the division operator compared to `magnitude`:

* For two finite operands, `magnitude` always defers to the underlying division operation, whereas my implementation checks the denominator.
    * 1.0 / 0.0 with floating-point values in `magnitude` defers to the underlying operation and results in a "finite" value of floating-point infinity, whereas in my implementation this results in a "proper" `Infinity`.
    * 0.0 / 0.0 in `magnitude` results in a "finite" value of NaN, whereas in my implementation this results in a panic.
* Division by zero is always undefined in `magnitude`, whereas only zero divided by zero is undefined in my implementation.
* A nonzero finite number divided by an infinite value is undefined in `magnitude`, whereas in my implementation this results in zero.

**Comment by kyp44** [comment]
I like the way you've made division work as described above, and it seems clearly advantageous compared to how `magnitude` does it.

**Comment by kyp44** [comment]
Is this work sufficiently complete that you can cut a new release on `crates.io`?

**Comment by ObjectBoxPC** [comment]
@kyp44 I just released v1.5.0 with this functionality. Thanks for your feedback on this feature!

**Pull request merged**
